### ISSUE TITLE
Eventemitter

### ISSUE THREAD

**Issue by simon-p-r** [bennycooly/node-cec-client#1]
Hi 

Did you ever get an event emitter working?  Your code appears to be incomplete, I have similar need to get a c callback invoked into javascript.

Thanks

**Comment by benfuu** [comment]
Hey,

I never had time to finish this project because of school but I might continue to work on it in a few months. You should be able to get the callbacks working by using an object reference to the Node EventEmitter

**Comment by simon-p-r** [comment]
No worries I just found this project if you are interested https://github.com/devsnek/eventemitter-native
